kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP     
- role: worker
  extraMounts:
  - hostPath: index.html
    containerPath: /demo/index.html
    readOnly: true
- role: worker
  extraMounts:
  - hostPath: index.html
    containerPath: /demo/index.html

